# Generated by Django 3.2.6 on 2021-08-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
