# Generated by Django 3.2.6 on 2021-08-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room_no',
            field=models.CharField(max_length=200),
        ),
    ]
